import { Redirect } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, ScrollView, StyleSheet, TextInput } from "react-native";

import { ExplorationMap } from "@/components/ExplorationMap";
import { AppPressable as Pressable } from "@/components/AppPressable";
import { AppShell } from "@/components/AppShell";
import { AppText as Text } from "@/components/AppText";
import { AppView as View } from "@/components/AppView";
import { useAppPreferences } from "@/context/AppPreferencesContext";
import { useAuth } from "@/context/AuthContext";
import { deleteExploration, getExploration, relocateExploration, updateExploration, type ExplorationResponse, type ExplorationVisit } from "@/services/lifeExplorationApi";

export default function ExplorationScreen() {
  const { authorizedRequest, status } = useAuth(); const { colors, theme } = useAppPreferences(); const styles = createStyles(colors, theme);
  const [data, setData] = useState<ExplorationResponse | null>(null); const [country, setCountry] = useState(""); const [city, setCity] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState<ExplorationVisit | null>(null);
  const load = useCallback(async () => { if (status !== "authenticated") return; setLoading(true); setError(null); try { setData(await getExploration(authorizedRequest)); } catch (caught) { setError(caught instanceof Error ? caught.message : "探索紀錄載入失敗"); } finally { setLoading(false); } }, [authorizedRequest, status]);
  useEffect(() => { void load(); }, [load]);
  const visits = useMemo(() => [...(data?.markers.flatMap((marker) => marker.visits) ?? []), ...(data?.unlocated ?? [])].filter((item) => (!country || item.country_name === country) && (!city || item.city_name === city)), [city, country, data]);
  const markers = useMemo(() => (data?.markers ?? []).filter((marker) => marker.visits.some((item) => (!country || item.country_name === country) && (!city || item.city_name === city))).map((marker) => ({ id: `${marker.latitude}-${marker.longitude}`, latitude: marker.latitude, longitude: marker.longitude, title: marker.title, type: `${marker.visits.length} 次造訪` })), [city, country, data]);
  if (status === "guest") return <Redirect href="/login" />;
  return <AppShell title="探索地圖"><View style={styles.intro}><Text style={styles.heading}>走過的地方，都留在地圖上</Text><Text style={styles.muted}>探索紀錄只能由收藏清單的「已造訪」或完成旅遊行程建立。</Text></View>{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Pressable onPress={() => void load()} style={styles.error}><Text style={styles.errorText}>{error}，點此重試</Text></Pressable> : null}{data ? <><Filter label="國家" options={data.filters.countries} styles={styles} value={country} onChange={(value) => { setCountry(value); setCity(""); }} /><Filter label="區域／城市" options={data.filters.cities} styles={styles} value={city} onChange={setCity} /><ExplorationMap markers={markers} /><View style={styles.list}>{visits.length ? visits.map((item) => <View key={item.id} style={styles.card}><Text style={styles.title}>{item.title}</Text><Text style={styles.muted}>{item.start_date}｜{[item.country_name, item.city_name].filter(Boolean).join("・")}</Text>{item.address ? <Text style={styles.muted}>{item.address}</Text> : null}{item.notes ? <Text style={styles.description}>{item.notes}</Text> : null}<View style={styles.actions}><Pressable onPress={() => setEditing(item)} style={styles.chip}><Text style={styles.chipText}>編輯</Text></Pressable><Pressable onPress={() => Alert.alert("確認刪除探索紀錄？", "只刪除此造訪快照，不影響原收藏或行程。", [{ text: "取消" }, { text: "刪除", style: "destructive", onPress: () => void deleteExploration(authorizedRequest, item.id).then(load) }])} style={styles.delete}><Text style={styles.deleteText}>刪除</Text></Pressable></View></View>) : <Text style={styles.empty}>目前沒有符合條件的探索紀錄</Text>}</View></> : null}{editing ? <EditVisit initial={editing} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} request={authorizedRequest} /> : null}</AppShell>;
}

function EditVisit({ initial, onClose, onSaved, request }: { initial: ExplorationVisit; onClose: () => void; onSaved: () => Promise<void>; request: ReturnType<typeof useAuth>["authorizedRequest"] }) { const { colors, theme } = useAppPreferences(); const styles = createStyles(colors, theme); const [date, setDate] = useState(initial.start_date); const [address, setAddress] = useState(initial.address ?? ""); const [notes, setNotes] = useState(initial.notes ?? ""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const save = async (relocate: boolean) => { setSaving(true); setError(null); try { await updateExploration(request, initial.id, { visited_on: date, address: address.trim() || undefined, notes: notes.trim() || undefined }); if (relocate) await relocateExploration(request, initial.id); await onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : "探索紀錄目前無法更新"); } finally { setSaving(false); } }; return <Modal transparent visible><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.heading}>編輯探索紀錄</Text><Text style={styles.label}>造訪日期</Text><TextInput onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.textMuted} style={styles.input} value={date} /><Text style={styles.label}>地址</Text><TextInput onChangeText={setAddress} placeholder="請輸入地址" placeholderTextColor={colors.textMuted} style={styles.input} value={address} /><Text style={styles.label}>備註</Text><TextInput multiline onChangeText={setNotes} placeholder="造訪備註" placeholderTextColor={colors.textMuted} style={[styles.input, styles.multiline]} value={notes} />{error ? <Text style={styles.errorText}>{error}</Text> : null}<View style={styles.actions}><Pressable onPress={onClose} style={styles.chip}><Text style={styles.chipText}>取消</Text></Pressable><Pressable disabled={saving} onPress={() => void save(false)} style={styles.chip}><Text style={styles.chipText}>僅儲存</Text></Pressable><Pressable disabled={saving} onPress={() => void save(true)} style={styles.chipActive}>{saving ? <ActivityIndicator color={colors.white} /> : <Text style={styles.chipActiveText}>儲存並重新定位</Text>}</Pressable></View></View></View></Modal>; }
function Filter({ label, onChange, options, styles, value }: { label: string; onChange: (value: string) => void; options: string[]; styles: ReturnType<typeof createStyles>; value: string }) { return <View style={styles.filterGroup}><Text style={styles.label}>{label}</Text><ScrollView horizontal contentContainerStyle={styles.filters} showsHorizontalScrollIndicator={false}><Pressable onPress={() => onChange("")} style={[styles.chip, !value && styles.chipActive]}><Text style={[styles.chipText, !value && styles.chipActiveText]}>全部</Text></Pressable>{options.map((option) => <Pressable key={option} onPress={() => onChange(option)} style={[styles.chip, value === option && styles.chipActive]}><Text style={[styles.chipText, value === option && styles.chipActiveText]}>{option}</Text></Pressable>)}</ScrollView></View>; }
const createStyles = (colors: ReturnType<typeof useAppPreferences>["colors"], theme: ReturnType<typeof useAppPreferences>["theme"]) => StyleSheet.create({ intro: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, gap: 5, padding: 17 }, heading: { color: colors.text, fontSize: 20, fontWeight: "900" }, muted: { color: colors.textMuted, fontSize: 13, lineHeight: 20 }, filterGroup: { gap: 7 }, label: { color: colors.text, fontWeight: "800" }, filters: { gap: 8 }, chip: { backgroundColor: colors.primarySoft, borderRadius: 17, paddingHorizontal: 13, paddingVertical: 8 }, chipActive: { backgroundColor: colors.primary, borderRadius: 10, paddingHorizontal: 15, paddingVertical: 10 }, chipText: { color: colors.primaryDark, fontWeight: "700" }, chipActiveText: { color: theme === "dark" ? colors.background : colors.white, fontWeight: "800" }, list: { gap: 10 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, gap: 5, padding: 15 }, title: { color: colors.text, fontSize: 16, fontWeight: "900" }, description: { color: colors.text, lineHeight: 21 }, empty: { color: colors.textMuted, textAlign: "center" }, error: { backgroundColor: colors.surface, padding: 14 }, errorText: { color: colors.danger, fontWeight: "700" }, actions: { flexDirection: "row", gap: 8, justifyContent: "flex-end", marginTop: 6 }, delete: { borderColor: colors.danger, borderRadius: 10, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 8 }, deleteText: { color: colors.danger, fontWeight: "800" }, modalBackdrop: { alignItems: "center", backgroundColor: "rgba(13,30,27,.55)", flex: 1, justifyContent: "center", padding: 16 }, modalCard: { backgroundColor: colors.surface, borderRadius: 18, gap: 12, maxWidth: 520, padding: 22, width: "100%" }, input: { backgroundColor: theme === "dark" ? colors.background : colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, fontSize: 16, padding: 11 }, multiline: { minHeight: 90, textAlignVertical: "top" } });
